export enum ACTIVITY_TYPE_ENUM {
  COMMON,
  REGISTRATION_ONLY,
  SSC,
  KK,
  LMD,
  INVENTRA,
  KOMPROF,
  SPECTRA,
  SUB_PROGRAM,
}

export enum ACTIVITY_CATEGORY_ENUM {
  PELATIHAN,
  KEASRAMAAN,
  KADERISASI,
  AKTUALISASI_DIRI,
  KEALUMNIAN,
}

export enum ACTIVITY_REGISTRANT_STATUS_ENUM {
  BELUM_TERDAFTAR = "BELUM TERDAFTAR",
  TERDAFTAR = "TERDAFTAR",
  DITERIMA = "DITERIMA",
  LULUS_KEGIATAN = "LULUS KEGIATAN",
  TIDAK_LULUS = "TIDAK LULUS",
  TIDAK_DITERIMA = "TIDAK DITERIMA",
}
