export enum USER_LEVEL_ENUM {
  JAMAAH,
  AKTIVIS,
  AKTIVIS_KK,
  KADER,
  KADER_INVENTRA,
  KADER_KOMPROF,
  KADER_LANJUT,
}

export enum ACTIVITY_CATEGORY_ENUM {
  PELATIHAN,
  KEASRAMAAN,
  KADERISASI,
  AKTUALISASI_DIRI,
  KEALUMNIAN,
}

export enum ACTIVITY_REGISTRATION_DEFAULT_ENUM {
  BELUM_TERDAFTAR = "BELUM TERDAFTAR",
  TERDAFTAR = "TERDAFTAR",
  DITERIMA = "DITERIMA",
  LULUS_KEGIATAN = "LULUS KEGIATAN",
  TIDAK_LULUS = "TIDAK LULUS",
  TIDAK_DITERIMA = "TIDAK DITERIMA",
}
